### ISSUE TITLE
Return addresses in encoded form

### ISSUE THREAD

**Issue by dgarcia360** [symbol/symbol-openapi#182]
REST responses are returned in the decoded form (e.g. 90340017CFF3DD2BCF3B2670CDCB9FC8C75754E2325F297C), but client apps use the encoded (SA2AAF6P6POSXTZ3EZYM3S47ZDDVOVHCGJPSS7A) form.
To enhance the developer experience, the responses must return addresses encoded.

**Implementation notes:**

https://github.com/nemtech/catapult-rest/blob/master/catapult-sdk/src/model/address.js#L58 should be called when formatting instead of formatting as byte array.

**Comment by Vektrat** [comment]
there are other impacts with this change, when clients provide addresses as params... i suppose those should be changed as well?

**Comment by dgarcia360** [comment]
Address query params supported encoded addresses even before pagination changes were applied (e.g. `recipientAddress=SA2AAF6P6POSXTZ3EZYM3S47ZDDVOVHCGJPSS7A`). The change proposed would only affect resolved addresses responses.

However, there is an issue with the current API design and the use of aliases. Some address query params support encoded addresses for unresolved addresses, but it does not look right to pass the id encoded as an address.

For this reason, it would be best either to:

* Use unresolved addresses decoded for query params (e.g. recipientAddress=90340017CFF3DD2BCF3B2670CDCB9FC8C75754E2325F297C)
* (Prefered) Detect between namespaceIds or decoded addresses (e.g. recipientAddress=SA2AAF6P6POSXTZ3EZYM3S47ZDDVOVHCGJPSS7A or recipientAddress=941299B2B7E1291C) and format unresolved addresses responses accordingly.

**Comment by Vektrat** [comment]
do we think it makes sense to allow querying by alias (namespaceId)? due to its nature, probably not - what is the client expecting when doing so?

- either REST resolves to its current value (which is changing and unsafe), so querying by using one alias today, might be different (different address) than querying by using the same alias tomorrow
- or either it just gets resources that have used this namespaceId at any given time, even if its linked address has changed (which means we would get a lot of resources that are using this namespaceId, but they would belong to different addresses)

**Comment by Vektrat** [comment]
related: https://github.com/nemtech/catapult-rest/issues/436
